Version: 1.1.0.1 - First functional MinGW version (without help)
This version is being released as 1.1.0.1 since it should be
functionally identical to 1.1.0.0 except that it has been compiled with
the MinGW compiler and it does not include a help system.

This version was developed on a separate windows computer with a locally
installed version of Git. The fine-grained changes were tracked in Git
on that computer, but they are aggregated here in this commit. The
commit messages are included below.

Hashes:
  $ sha1sum Reconstruct.exe
    2cd2da36ebdb328a3e9c7d5dfea4f801f21d1f4b
  $ sha256sum Reconstruct.exe
    8bc4a87099685907e52e9fee14da76248a060e828738f6200fa7a06d2dfa0e8c

======= Commits from Windows Machine =======

  commit dcf0dea88523441c23ba94089ca2fb3a40b42789
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 04:16:02 2018 -0700

    Just recompiled.

  commit aa642590891a4c813e06603c987a86eebb6007f1
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 04:10:36 2018 -0700

    Updating the documentation

  commit b5ed7810842fe948104a2d0ce4a4472fc237e334
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 04:01:58 2018 -0700

    Removed some of the testing bitmaps.

  commit ea94f3ea3034bd4145949a01bb73c31b9d706ac1
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 03:59:51 2018 -0700

    This version has all of the resources added except the help menus.

    The help menu system depends on some things that make it unique.

  commit d689b2fee0e21cae0427bfe1e012676a3b779597
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 03:54:12 2018 -0700

    More resources ... all working so far.

  commit 944c8c61f03afb377055b85ddf5dc08e4938b589
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 03:50:50 2018 -0700

    Added more resources ... finding a number of errors.

  commit 3b656008920c680f7df936045b52989bbf844245
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 03:36:28 2018 -0700

    More menu resources - Note that "3DMenu" was changed to "T3DMenu"

  It appears that this compiler doesn't like the identifier starting
  with number. This will need to be changed somewhere in the code to
  match.

    Also note that several commas were missing from the .RC file.

  commit 61fe95bb690b50fd414c600356f2b87e2a45c0bb
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 03:29:09 2018 -0700

    More progress on the resources...

  commit f317c0e36bf036f66faacaf85582bbda3540cf4e
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 03:25:34 2018 -0700

    Added more resources ... this version is working.

  commit 31ce5da792f37faa8440e827665a9e46c0554a29
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 03:18:41 2018 -0700

    Adding more of the resource file ... some of it was failing.

  commit 96f05214c43490c4dcc8a6889ee914ff94946e08
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 03:03:39 2018 -0700

    This version can be built with makefile_raw!!!

  commit 5db5969349f236a8e2a690b1ece16ab0d9ac0376
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Fri Mar 23 02:44:19 2018 -0700

    This version compiled with resources!!

  commit ebeed55354a3062dd5725654d26b6e07a8094f49
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Wed Mar 21 22:43:49 2018 -0700

    First version to compile, link, and run  ...  no help.

    Commented out the HtmlHelp calls in help_menu.cpp and it compiled,
    linked, and ran.

    However, because there were no resources in the project, the windows
    came up empty (no menus and no icons).

    More work to be done.

  commit 84d6552e6ffa4a3522b4fd578afcf843193b3752
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Wed Mar 21 22:37:38 2018 -0700

    Added .gitignore and Reconstruct.layout before creating branch

  commit a3ec16f187dfbe51ccef75542cdfa4c7f7664fcb
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Wed Mar 21 22:30:00 2018 -0700

    Added two more libraries to the project. Almost builds.

    This version only has one linking error:

      help_menu.o help_menu.cpp: undefined reference to 'HtmlHelpA'

    That error happens 3 times in help_menu.cpp.

    I will create a "no_help" branch an comment those lines.

  commit 52903aa0b92c9f4c0e9395e94fa5af32b24b1052
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Wed Mar 21 22:01:29 2018 -0700

    Added libversion

    Added a library to the project options at:

      c:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib
          libversion.a

  commit ec64fda13e05003c36aa0441f19d5a86144ff1cb
  Author: Bob Kuczewski <bobkuczewski@salk.edu>
  Date:   Wed Mar 21 21:53:39 2018 -0700

    Added Dev-CPP project file and generated Makefile.win

    This project is being build as a Dev-C++ project which includes:

      Reconstruct.dev  - This is the project file used by Dev-C++
      Makefile.win     - This is the makefile generated by Dev-C++